# -*- coding: utf-8 -*-
"""numpy_examples.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nYB-FxkvtS_bUasiyb1h_kWvXkZL6fHh
"""

import numpy as np



dizi = np.array([1, 2, 3, 4, 5])

print(dizi)



# İki Boyutlu Dizi (Matris)

matris = np.array([[1, 2, 3], [4, 5, 6]])

print(matris)



# 0 ve 1'lerden olusan 3x3'lük matris

sifirlar = np.zeros((3, 3))

print(sifirlar)

birler = np.ones((2, 4))

print(birler)



# Belirli aralıktaki sayılar

aralik=np.arange(0,10,2)

print(aralik)

aralik=np.arange(0,10,2)
print(aralik)

esit_aralik=np.linspace(0,1,4
                        )
print(esit_aralik)

rastgele=np.random.rand(3,3)
print(rastgele)

#diziler üzerindeki matematiksel işlemler
dizi1=np.array([1,2,3])
dizi2=np.array([4,5,6])
toplam=dizi1+dizi2

toplam

dizi=np.array([1,2,3,4,5])
print("Toplam",np.sum(dizi))
print("Ortlama",np.mean(dizi))
print("Max",np.max(dizi))
print("Min",np.min(dizi))

#shape ve reshape
dizi=np.arange(1,10)
print(dizi)

yeniden=dizi.reshape(3,3)
print(yeniden)

#filtrelem
dizi=np.array([10,20,30,40,50])
#listede 30 dan büyük sayıları yazdır
filtre=dizi[dizi>30]
filtre

dizi1=np.array([1,2,3])
matris=np.array([[1,1,1],[2,2,2]])
sonuc=dizi1+matris
sonuc

dizi=np.array([1,4,9,16,25])
karekok=np.sqrt(dizi)
karekok

data=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(data)

sutun_ortalama=np.mean(data,axis=0)
print(sutun_ortalama)
satir_toplam=np.sum(data,axis=1)
print(satir_toplam)
#axis=1 satır
#axis=0 sütun

randDizi=np.random.randint(0,100,20)
randDizi

randDizi.argmax()

reshapedizi=randDizi.reshape(5,4)

reshapedizi.shape

randDizi[3:8]=0
randDizi

