# -*- coding: utf-8 -*-
"""pandas_examples.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g3yzxsLv6MJfc1h2QQoyoNFkFDBa-Cal
"""

import numpy as np
import pandas as pd

dict_ex={"AA":23,"BB":23,"CC":20}
pd.Series(dict_ex)

ages=[10,20,30]
names=["a","b","c"]
pd.Series(ages,names)

np_dizi=np.array([50,40,30])
pd.Series(np_dizi,names)

pd.Series(["d","e","f"],[1,2,3])

com1=pd.Series([10,20,30],["a","b","c"])
com2=pd.Series([10,5,3],["d","a","c"])
last_comp=com1+com2
last_comp

"""**Data frame**"""

data=np.random.randn(4,3)
dataFrame=pd.DataFrame(data)
dataFrame

newDataFrame=pd.DataFrame(data,index=["a","b","c","d"],columns=["kolon1","kolon2","kolon3"])
newDataFrame

newDataFrame["kolon1"]

newDataFrame.loc["a"]

newDataFrame.iloc[1]

newDataFrame["yeni kolon"]=newDataFrame["kolon1"]+newDataFrame["kolon2"]
newDataFrame

newDataFrame.drop("yeni kolon",axis=1)

newDataFrame.drop("c")

newDataFrame

newDataFrame.drop("yeni kolon",axis=1,inplace=True)#halıcı olarak değişiklıik kaydetme
newDataFrame

newDataFrame.loc["a"]["kolon1"]
newDataFrame.loc["a","kolon1"]

newDataFrame[newDataFrame["kolon1"]>0]

newDataFrame.reset_index()

new_list=["n1","n2","n3","n4"]
newDataFrame["new_list"]=new_list
newDataFrame

newDataFrame.set_index("new_list")

newDataFrame

newDataFrame.set_index("new_list",inplace=True)
newDataFrame

"""**multi index**

"""

ilk_index=["a","a","a","b","b","b"]
ic_index=[1,2,3,1,2,3]
birlesmis_index=list(zip(ilk_index,ic_index))
birlesmis_index

birlesmis_index=pd.MultiIndex.from_tuples(birlesmis_index)
birlesmis_index

my_list=np.array([[10,"a"],[20,"b"],[30,"c"],[40,"d"],[50,"e"],[60,"f"]])
my_list

dataFrame=pd.DataFrame(my_list,index=birlesmis_index,columns=["sayı","harf"])
dataFrame

dataFrame.index.names=["ilk index","ic index"]
dataFrame

"""**eksik veriler**"""

hava_durumu_dataFrame=pd.DataFrame({"İstanbul":[30,29,np.nan],"Ankara":[20,np.nan,25],"İzmir":[40,39,38]})
hava_durumu_dataFrame

hava_durumu_dataFrame.dropna(axis=1)

hava_durumu_dataFrame["Antalya"]=[45,np.nan,np.nan]
hava_durumu_dataFrame

hava_durumu_dataFrame.dropna(axis=1,thresh=2)

hava_durumu_dataFrame.fillna("-")

"""**group** **by**

"""

salary_dict={"Departman":["Yazılım","Yazılım","Satış","Satış","Hukuk","Hukuk"],
             "Çalışanlar":["Ahmet","Mehmet","Ayşe","Fatma","Zeynep","Ali"],
             "Maaş":[100,150,200,300,400,500]

             }

salary_dataFrame=pd.DataFrame(salary_dict)
grup=salary_dataFrame.groupby("Departman")
grup.min()

grup.max()

grup.describe()

"""**concat**"""

dict1={"isim":["ahmet","mehmet","zeynep","atıl"],
       "spor":["koşu","yüzme","koşu","basketbol"],
       "kalori":[100,500,300,400]
       }
df1=pd.DataFrame(dict1,index=[0,1,2,3])
df1

dict2={"isim":["osman","levent","atlas","fatma"],
       "spor":["koşu","yüzme","koşu","basketbol"],
       "kalori":[100,500,30,100]}
df2=pd.DataFrame(dict2,index=[4,5,6,7])
df2

dict3={"isim":["ayse","mahmut","duygu","nur"],
       "spor":["koşu","yüzme","badminton","tenis"],
       "kalori":[100,500,300,400]}
df3=pd.DataFrame(dict3,index=[8,9,10,11])
df3

pd.concat([df1,df2,df3],axis=0)

"""**merge**"""

m_dict1={"isim":["ahmet","mehmet","zeynep","atıl"],
       "spor":["koşu","yüzme","koşu","basketbol"]}
m_df1=pd.DataFrame(m_dict1)
m_df1

m_dict2={"isim":["ahmet","mehmet","zeynep","atıl"],
       "kalori":[100,500,300,400]}
m_df2=pd.DataFrame(m_dict2)
m_df2

pd.merge(m_df1,m_df2,on="isim")

maasSozluk={"isim":["ahmet","mehmet","atıl","zeynep"],
            "departman":["yazılım","satış","pazarlama","yazılım"],
            "maas":[100,150,200,120]
            }
maasDataFrame=pd.DataFrame(maasSozluk)
maasDataFrame

maasDataFrame["departman"].unique()

maasDataFrame["departman"].nunique()

maasDataFrame["departman"].value_counts()

def bruttenNete(maas):
    return maas*0.66

maasDataFrame["maas"].apply(bruttenNete)

maasDataFrame.isnull()

yeni_veri={"karakter sınıfı":["south","south","simpson","simpson"],
           "karakter ismi":["cartman","kenny","homer","bart"],
           "karakter yas":[9,10,50,20]
           }
yeni_veri_dataFrame=pd.DataFrame(yeni_veri)
yeni_veri_dataFrame

yeni_veri_dataFrame.pivot_table(values="karakter yas",index=["karakter sınıfı","karakter ismi"])