# -*- coding: utf-8 -*-
"""tensorflow_last_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19duQuRzJH7-6cUI9sYL6I1WOk1Oyk7CA
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn

dataFrame=pd.read_excel("merc.xlsx")

dataFrame.head()

dataFrame.describe()

dataFrame.isnull().sum()

sbn.displot(dataFrame["price"])#verinin sağa doğru olan uzayan kısmı veriyi bozuyo sapmayı artırıyor

sbn.scatterplot(x="mileage",y="price",data=dataFrame)

yuzde_doksan_dokuz_DF=dataFrame.sort_values("price",ascending=False).iloc[131:]

sbn.distplot(yuzde_doksan_dokuz_DF["price"])

dataFrame=yuzde_doksan_dokuz_DF

dataFrame=dataFrame[dataFrame.year != 1970]

dataFrame=dataFrame.drop("transmission",axis=1)

y=dataFrame["price"].values
x=dataFrame.drop("price",axis=1).values

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=10)

from sklearn.preprocessing import MinMaxScaler

scaler= MinMaxScaler()

x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

x_train.shape

model=Sequential()
model.add(Dense(12,activation="relu"))
model.add(Dense(12,activation="relu"))
model.add(Dense(12,activation="relu"))
model.add(Dense(12,activation="relu"))
model.add(Dense(1))
model.compile(optimizer="adam",loss="mse")

model.fit(x=x_train,y=y_train,validation_data=(x_test,y_test),batch_size=250,epochs=300)

loss_data=pd.DataFrame(model.history.history)
loss_data.plot()

from sklearn.metrics import mean_squared_error,mean_absolute_error

tahmin_dizisi=model.predict(x_test)

mean_absolute_error(y_test,tahmin_dizisi)

plt.scatter(y_test,tahmin_dizisi)
plt.plot(y_test,y_test,"g--")

dataFrame.iloc[2]

